### ISSUE TITLE
Can we use Issues as some sort of repository suggestions? Thanks

### ISSUE THREAD

**Issue by vedrecide** [Coders-System/coders-bot#1]

**Comment by FlasH1719** [comment]
good idea, maybe tag it with a suggestion or feature request tag

**Comment by vedrecide** [comment]
Yeah, its not a default github repo feature, but ahnaf can configure it i hope lol

**Comment by ahnaf-zamil** [comment]
Yes, you can. The default GitHub tags are adequate, but I will configure some more. Closing.

**Comment by FlasH1719** [comment]
> Yeah, its not a default github repo feature, but ahnaf can configure it i hope lol

we can create labels so not a problem unless ahnaf doesn't like it
