### ISSUE TITLE
Add a starboard system..

### ISSUE THREAD

**Issue by vedrecide** [Coders-System/coders-bot#5]
Ayyeeeeee just replace the starboard bot, kinda useless especially to use the thing regardless it doesn
't have anything else and basically, we can add anything we want in the coder's bot especially

**Comment by 1olipop** [comment]
Ayyeeeeee just replace the starboard bot, kinda useless especially to use the thing regardless it doesn
't have anything else and basically, we can add anything we want in the coder's bot especially

**Comment by ahnaf-zamil** [comment]
Yes, you are right. Since we don't use Auttaja anymore (replaced by Vortex) we are using the starboard bot for all of our starboard stuff. But I don't fancy having a mod bot only for starboard; so that's why, putting starboard features in Coder's Bot.

Any feedback is appreciated

**Comment by ahnaf-zamil** [comment]
I'm gonna start working on the starboard system, so I will assign myself.
